
language: python
python:
  - 2.7
  - 3.6

env:
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.5

before_install:
  - pip install -r requirements.txt

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install django-crispy-forms

script: python manage.py test

