
language: python # language
python: # versions
  - 3.6

services: postgresql

env:
  - export DJANGO_SETTINGS_MODULE = vacations.settings

install: # install requirements with installed packages
  - pip install -r requirements.txt

before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres

script: # manage.py script to run the tests
  - python manage.py test

notifications:
  slack:
    rooms:
      - theknowlesfamily:BJuivdSBRW1hWWBW7X6jhspc#notifications
    on_success: always
    on_failure: always

deploy:
  - provider: s3
    ⋮ # rest of S3 deployment for MyApp.zip
  - provider: codedeploy
    access_key_id: "YOUR AWS ACCESS KEY"
    secret_access_key: "YOUR AWS SECRET KEY"
    bucket: "S3 Bucket"
    key: latest/MyApp.zip
    application: MyApp
    deployment_group: MyDeploymentGroup
