
language: python # language
python: # versions
  - 3.6

install: # install requirements with installed packages
  - pip install -r requirements.txt

script: # manage.py script to run the tests
  - python manage.py test

