# Generated by Django 2.0.2 on 2018-03-02 19:32

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('minneapolis', django.db.models.manager.Manager()),
            ],
        ),
    ]
