# Generated by Django 2.0.2 on 2018-03-15 19:23

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180305_1727'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('minneapolis', django.db.models.manager.Manager()),
            ],
        ),
    ]
