# Generated by Django 2.0.2 on 2018-04-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.CharField(default='', max_length=255),
        ),
    ]
