# Generated by Django 2.0.2 on 2018-04-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_exercise_exercise_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
